[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
cache_path = "cache_forge"
broadcast = "broadcast"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
via_ir = true
ast = true
build_info = true
build_info_path = "out/build-info"
extra_output = ["storageLayout"]
extra_output_files = ["metadata"]
force = true
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./" }
]

remappings = ['@openzeppelin=lib/openzeppelin-contracts/','@openzeppelin/upgradeable=lib/openzeppelin-contracts-upgradeable/','@openzeppelin/upgrades=lib/openzeppelin-foundry-upgrades/']

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
celo = "${CELO_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
amoy = "${POLYGON_AMOY_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
alfajores = "${CELO_ALFAJORES_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
celo = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
